### PR TITLE
Complete refactor of the ion plugin to use Kotlin and support future versions of IntelliJ.

### PR DESCRIPTION
**Pull request by belloale**
Creating V2 of the Amazon Ion plugin which provides several improvements to Ion syntax highlighting.

*Description of changes:*

Complete refactor of the ion plugin to use Kotlin and support future versions of IntelliJ. Bumping the plugin version to 2.0 and make several improvements to Ion Syntax highlighting.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by zslayton** [comment]
Hi, thanks for the PR! The diff for this is quite extensive and I was wondering whether you would be willing to break it down a bit for easier review. Relatively few of the 300+ files that were updated seem to contain interesting logic changes.

It would be helpful to have separate commits for:
1. Removing files (both source files and build artifacts) from the old version.
2. The (presumably automated?) change that was made to add `@NotNull` and `@Overrides` to several dozen classes.
3. Adding all of the new files containing the updated plugin logic.

If you could give a high-level overview of the files in \#3, that would also be appreciated. There are dozens of files and unfortunately GitHub likes to alphabetize them, which isn't always the most sensible ordering. Where's the best place for a reader to start?

**Comment by belloale** [comment]
Hey zslayton@, sure I can break this into smaller PRs as mentioned. Just to be clear, the intention was to just completely wipe the existing plugin code and start over anew.

**Comment by belloale** [comment]
PR for 1. https://github.com/amzn/ion-intellij-plugin/pull/14

**Comment by zslayton** [comment]
> Hey zslayton@, sure I can break this into smaller PRs as mentioned.

I was looking for separate commits, not necessarily full-blown PRs, as that would still allow me/others to filter out a few hundred files as we went to review it.

**Pull request closed without merging**
