### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by surajsahani**
*Issue #, if available:* No issue available

*Description of changes:* improving readme

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by hiljusti** [comment]
I'm curious why you think this improves the readme. To me, it seems to mix cases in a way that doesn't really match anything else (`ion-intellij-plugin` is the repository name)

I suppose if the readme title was to update, maybe it could be something like `Amazon Ion - IntelliJ Plugin` to match [the plugin name](https://plugins.jetbrains.com/plugin/8409-amazon-ion). My preference would be to keep the all-lowercase repository name.

**Comment by surajsahani** [comment]
@hiljusti I was following the Wikipedia guide everywhere it is used as "IntelliJ" so. just a little contribution :)
https://en.wikipedia.org/wiki/IntelliJ_IDEA

**Comment by hiljusti** [comment]
I'd still suggest to either keep the all-lowercase style as it is now (more formally: to use [kebab-case](https://winnercrespo.com/naming-conventions/)) or to convert the entire thing to proper nouns and their proper casing (more formally: use English rules)

Changing the casing for only one character of 3 words reduces readability from my perspective.

**Comment by surajsahani** [comment]
okay, thank you

**Pull request closed without merging**
